import streamlit as st
st.title("Pengertian Diabetes")
st.write("Diabetes melitus atau yang dikenal dengan kencing manis merupakan penyakit dimana kadar gula dalam darah cukup tinggi karena tubuh tidak dapat menggunakan insulin sehingga gula didalam darah tidak dapat dimetabolisme.")
st.image("diabetes-.jpg")
st.title("Gejala Diabetes")
st.write("A. Sering kencing")
st.write("B. Rasa haus berlebihan")
st.write("C. Rasa lapar berlebihan")
st.write("D. Mudah lelah")
st.write("E. Kadar gula darah tinggi")
st.write("F. Luka lambat sembuh")
st.title("Faktor Penyebab Diabetes")
st.write("Faktor genetik")
st.write("Obesitas dan berat badan berlebih")
st.write("Usia")
st.write("Hipertens")
st.write("Gangguan Toleransi Glukosa")
st.title("Cara Mengontrol Diabetes")
st.image("WhatsApp Image 2024-05-20 at 20.00.42_775b9586.jpg")
st.write("Diet Sehat dan Seimbang")
st.write("Olahraga Rutin")
st.write("Pemantauan Gula Darah")
st.write("Penggunaan Obat Secara Teratur")
st.write("Pemeriksaan Kesehatan Rutin")
st.write("Pemeriksaan Kesehatan Rutin")